runtime: go111

main: github.com/squee1945/threespot/server/cmd

automatic_scaling:
  max_concurrent_requests: 80
  
handlers:
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/images/favicon.png
  upload: static/images/favicon.png
- url: .*
  script: auto
  secure: always
