runtime: go111

main: github.com/squee1945/threespot/server/cmd

automatic_scaling:
  max_concurrent_requests: 80
  
handlers:
- url: /static/css
  static_dir: static/css

- url: /static/images
  static_dir: static/images
  expiration: 90d

- url: /static/scripts
  static_dir: static/scripts

- url: /favicon.ico
  static_files: static/images/favicon.png
  upload: static/images/favicon.png
  
- url: .*
  script: auto
  secure: always
